# Introduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
import numpy as np

#### 2. Print your NumPy version.

In [2]:
print(np.__version__)

1.23.5


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [3]:
a = np.random.randint(low=0, high=90, size = (2, 3, 5))

In [86]:
a_2 = np.random.rand(2, 3, 5)
a_2

array([[[0.67687109, 0.05936177, 0.53827098, 0.34033149, 0.63612094],
        [0.53553192, 0.55325528, 0.12607709, 0.83145631, 0.42667384],
        [0.7322595 , 0.08733457, 0.01393136, 0.65555255, 0.18267269]],

       [[0.23465748, 0.52453559, 0.45842954, 0.94255785, 0.10933735],
        [0.62689475, 0.41966769, 0.70813256, 0.54680675, 0.22073327],
        [0.29072601, 0.10292449, 0.22721111, 0.17443634, 0.28718508]]])

In [98]:
a_3 = np.random.choice(range(0,100), size=(2, 3, 5))
a_3

array([[[37, 83,  7, 20,  6],
        [73, 68, 19,  4, 10],
        [94,  1, 68, 69, 57]],

       [[85, 45, 15, 39, 39],
        [88, 51, 61, 31, 83],
        [23, 22, 32, 42, 67]]])

#### 4. Print *a*.


In [4]:
print(a)

[[[89 60 28 23 36]
  [18 61 52 10 22]
  [58  6 12  4 39]]

 [[ 3  1 89 18 28]
  [84 44 66 70 81]
  [42 89 52 33 84]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [99]:
b = np.ones((5,2,3))

#### 6. Print *b*.


In [6]:
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [7]:
a.size == b.size

True

#### 8. Are you able to add *a* and *b*? Why or why not?


In [8]:
c = a + b
# No, they have different shapes

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [100]:
c = np.transpose(b, (1,2,0))
c

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [10]:
d = a + c

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [11]:
print(a)
print(d)

# a has integer values and b has float values.
# each value of d is 1 higher than a as it is the sum of a and c.

[[[89 60 28 23 36]
  [18 61 52 10 22]
  [58  6 12  4 39]]

 [[ 3  1 89 18 28]
  [84 44 66 70 81]
  [42 89 52 33 84]]]
[[[90. 61. 29. 24. 37.]
  [19. 62. 53. 11. 23.]
  [59.  7. 13.  5. 40.]]

 [[ 4.  2. 90. 19. 29.]
  [85. 45. 67. 71. 82.]
  [43. 90. 53. 34. 85.]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [38]:
e = a * c

#### 13. Does *e* equal to *a*? Why or why not?


In [39]:
a == e
# they have the same values and shape, however, a has integers and e has floats.

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [36]:
d_max = d.max()
d_min = d.min()
d_mean = d.mean()

#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.

In [40]:
f = np.empty([2,3,5])
f

array([[[89., 60., 28., 23., 36.],
        [18., 61., 52., 10., 22.],
        [58.,  6., 12.,  4., 39.]],

       [[ 3.,  1., 89., 18., 28.],
        [84., 44., 66., 70., 81.],
        [42., 89., 52., 33., 84.]]])

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [68]:
f = np.array([[[100 if z == d_max else 75 if z > d_mean else 50 if z == d_mean else 25
                if z > d_min else 0 for z in d2]for d2 in d1]for d1 in d])

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [80]:
print('d:', d, '\n\n','f:', f)


d: [[[90. 61. 29. 24. 37.]
  [19. 62. 53. 11. 23.]
  [59.  7. 13.  5. 40.]]

 [[ 4.  2. 90. 19. 29.]
  [85. 45. 67. 71. 82.]
  [43. 90. 53. 34. 85.]]] 

 f: [[[100  75  25  25  25]
  [ 25  75  75  25  25]
  [ 75  25  25  25  25]]

 [[ 25   0 100  25  25]
  [ 75  75  75  75  75]
  [ 25 100  75  25  75]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [82]:
g = np.array([[['E' if z == d_max else 'D' if z > d_mean else 'C' if z == d_mean else 'B'
                if z > d_min else 'A' for z in d2]for d2 in d1]for d1 in d])
g

array([[['E', 'D', 'B', 'B', 'B'],
        ['B', 'D', 'D', 'B', 'B'],
        ['D', 'B', 'B', 'B', 'B']],

       [['B', 'A', 'E', 'B', 'B'],
        ['D', 'D', 'D', 'D', 'D'],
        ['B', 'E', 'D', 'B', 'D']]], dtype='<U1')